Spring security (#299)
* feat(docker): Very first try at automating the Jenkins test war deployment within the docker image.

* fix(docker): Pipeline title.

* fix(updatecli): Creates PRs on the right branch.

* fix(docker): Environment variables.

* fix(docker): Checks environment variables.

* fix(docker): Only tests one pipeline.

* fix(docker): If the environment variables are not being recognized in your bash script, it could be due to how the script is being executed. If the script is being run in a new shell process, it won't have access to the environment variables of the parent process (the GitHub Actions runner).

* fix(docker): I don't get it.

* fix(docker): echoing env

* fix(docker): echoing env

* fix(docker): echoing env

* fix(updatecli): Needs to specify the environment variable you want to share with the script.

 https://www.updatecli.io/docs/plugins/resource/shell/

* fix(updatecli): Preparing for the upstream repo.

diff --git a/.github/workflows/updatecli.yaml b/.github/workflows/updatecli.yaml
--- a/.github/workflows/updatecli.yaml
+++ b/.github/workflows/updatecli.yaml
@@ -25,19 +25,35 @@ jobs:
       - name: Install Updatecli in the runner
         uses: updatecli/updatecli-action@v2.59.0
 
+      - name: Check environment variables
+        run: |
+          if [[ -z "${JENKINS_USERNAME}" ]] || [[ -z "${JENKINS_API_TOKEN}" ]]; then
+            echo "Error: JENKINS_USERNAME and JENKINS_API_TOKEN must be set in the environment."
+            exit 1
+          fi
+        env:
+          JENKINS_USERNAME: ${{ secrets.JENKINS_USERNAME }}
+          JENKINS_API_TOKEN: ${{ secrets.JENKINS_API_TOKEN }}
+
       # This step runs Updatecli in Dry Run mode
       # It uses the "diff" command of updatecli with the specified config and values files
       # The GitHub token is passed as an environment variable
       - name: Run Updatecli in Dry Run mode
-        run: updatecli diff --config ./updatecli/updatecli.d --values ./updatecli/values.github-action.yaml
+        run: |
+          updatecli diff --config ./updatecli/updatecli.d --values ./updatecli/values.github-action.yaml
         env:
           UPDATECLI_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          JENKINS_USERNAME: ${{ secrets.JENKINS_USERNAME }}
+          JENKINS_API_TOKEN: ${{ secrets.JENKINS_API_TOKEN }}
 
       # This step runs Updatecli in Apply mode, but only if the current branch is 'main'
       # It uses the "apply" command of updatecli with the specified config and values files
       # The GitHub token is passed as an environment variable
       - name: Run Updatecli in Apply mode
-        if: github.ref == 'refs/heads/main'
-        run: updatecli apply --config ./updatecli/updatecli.d --values ./updatecli/values.github-action.yaml
+        if: github.ref == 'refs/heads/spring-security'
+        run: |
+          updatecli apply --config ./updatecli/updatecli.d --values ./updatecli/values.github-action.yaml
         env:
           UPDATECLI_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          JENKINS_USERNAME: ${{ secrets.JENKINS_USERNAME }}
+          JENKINS_API_TOKEN: ${{ secrets.JENKINS_API_TOKEN }}
